PREFIX ddc: <http://purl.org/NET/decimalised#>
PREFIX dpv: <https://w3id.org/dpv#>
PREFIX dcterm: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX hwbp: <https://hse-oahwb-profile.adaptcentre.ie#>
prefix dc: <http://purl.org/dc/elements/1.1/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX : <https://hse-oahwb-profile.adaptcentre.ie#>
PREFIX healthdcatap: <http://healthdata.dublinked.ie/def/healthdcatap#>

SELECT DISTINCT
?indicator 
?indicatorTitle
?numeratorSourceTitle 
?spatial 
?spatialResolutionInMeters
WHERE {
  ?indicator a dcat:Dataset ;
  dcterms:title ?indicatorTitle .
  ?indicator :numeratorSource ?numeratorSource .
  
  SERVICE<http://localhost:3030/datasets> {
    ?numeratorSource a dcat:Dataset ;
  		dcterms:title ?numeratorSourceTitle .
    OPTIONAL { ?numeratorSource dc:spatial ?spatial . }
    OPTIONAL { ?numeratorSource dcat:spatialResolutionInMeters ?spatialResolutionInMeters . }
  }
}