PREFIX : <https://hse.ie/>
PREFIX hseOntology: <https://hse.ie/ontology/>
PREFIX phi: <https://w3id.org/hse/ontology/phi#>
PREFIX phd: <https://w3id.org/hse/ontology/phd#>
PREFIX pht: <https://w3id.org/hse/terminology#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>

DELETE {
  ?dataset phi:numeratorSource ?sourceValue .
} INSERT {
  ?dataset phi:numeratorSource ?dataset2 .
} WHERE {
  ?dataset a dcat:Dataset ;
           phi:numeratorSource ?sourceValue .

  BIND(IRI(?sourceValue) AS ?dataset2)
};

DELETE {
  ?dataset phi:denominatorSource ?sourceValue .
} INSERT {
  ?dataset phi:denominatorSource ?dataset2 .
} WHERE {
  ?dataset a dcat:Dataset ;
           phi:denominatorSource ?sourceValue .

  BIND(IRI(?sourceValue) AS ?dataset2)
};

DELETE {
  ?dataset dcterms:provenance ?label .
} INSERT {
  ?dataset dcterms:provenance ?provenanceStatement .
} WHERE {
  ?dataset a dcat:Dataset ;
           dcterms:provenance ?label .

  ?provenanceStatement a dcterms:ProvenanceStatement ;
           rdfs:label ?label .
};

# replace dcterms:publisher uris
DELETE {
  ?s dcterms:publisher ?publisherStr .
} INSERT {
  ?s dcterms:publisher ?publisher .
} WHERE {
  ?s a dcat:Dataset ;
     dcterms:publisher ?publisherStr .

  ?publisher a dcterms:Publisher ;
     foaf:name ?publisherStr .
};
DELETE {
  ?dataset dcat:distribution ?distributionStr .
} INSERT {
  ?dataset dcat:distribution ?distribution .
} WHERE {
  ?dataset a dcat:Dataset ;
           dcat:distribution ?distributionStr .

  ?distribution a dcat:Distribution ;
           dcterms:format ?distributionStr .
};

# transform dcterms:accrualPeriodicity
DELETE {
  ?s dcterms:accrualPeriodicity ?accrualPeriodicityStr .
} INSERT {
  ?s dcterms:accrualPeriodicity ?accrualPeriodicity .
} WHERE {
  ?s a dcat:Dataset ;
     dcterms:accrualPeriodicity ?accrualPeriodicityStr .

  BIND(
    IF(?accrualPeriodicityStr = "EVERY_2_YEARS", pht:EVERY_2_YEARS, 
      IF(?accrualPeriodicityStr = "EVERY_3_YEARS", pht:EVERY_3_YEARS,
        IF(?accrualPeriodicityStr = "EVERY_4_YEARS", pht:EVERY_4_YEARS,
          IF(?accrualPeriodicityStr = "EVERY_5_YEARS", pht:EVERY_5_YEARS,
            IF(?accrualPeriodicityStr = "ANNUAL", pht:ANNUAL, 
              IF(?accrualPeriodicityStr = "MONTHLY", pht:MONTHLY,
                IF(?accrualPeriodicityStr = "QUARTERLY", pht:QUARTERLY,
                  IF(?accrualPeriodicityStr = "WEEKLY", pht:WEEKLY,
                    IF(?accrualPeriodicityStr = "DAILY", pht:DAILY,
                      IF(?accrualPeriodicityStr = "AS NEEDED", pht:AS_NEEDED,
                        IF(?accrualPeriodicityStr = "NEVER", pht:NEVER, pht:ANNUAL))))))))))
    ) AS ?accrualPeriodicity)
};