PREFIX : <https://hse.ie/>
PREFIX hseOntology: <https://hse.ie/ontology/>
PREFIX phi: <https://w3id.org/hse/ontology/phi#>
PREFIX phd: <https://w3id.org/hse/ontology/phd#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>

DELETE {
	?dataset phi:numeratorSource ?sourceValue .
} INSERT {
	?dataset phi:numeratorSource ?dataset2 .
	?dataset2 a dcat:Dataset ;
		dcterms:publisher ?publisher .
} WHERE {
	?dataset a dcat:Dataset ;
		phi:numeratorSource ?sourceValue .

	?publisher a dcterms:Publisher ;
		dcterms:source ?sourceValue .
	BIND(REPLACE(?sourceValue, "^.*/", "") AS ?lastSegment)
	BIND(IRI(CONCAT("https://hse.ie/data/id/", ?lastSegment)) AS ?dataset2)
};

DELETE {
	?dataset phi:denominatorSource ?sourceValue .
} INSERT {
	?dataset phi:denominatorSource ?dataset2 .
	?dataset2 a dcat:Dataset ;
		dcterms:publisher ?publisher .
} WHERE {
	?dataset a dcat:Dataset ;
		phi:denominatorSource ?sourceValue .

	?publisher a dcterms:Publisher ;
		dcterms:source ?sourceValue .
	BIND(REPLACE(?sourceValue, "^.*/", "") AS ?lastSegment)
	BIND(IRI(CONCAT("https://hse.ie/data/id/", ?lastSegment)) AS ?dataset2)
};

DELETE {
	?dataset dcterms:provenance ?label .
} INSERT {
	?dataset dcterms:provenance ?provenanceStatement .
} WHERE {
	?dataset a dcat:Dataset ;
		dcterms:provenance ?label .

	?provenanceStatement a dcterms:ProvenanceStatement ;
		rdfs:label ?label .
};

# replace dcterms:publisher uris
DELETE {
	?s dcterms:publisher ?publisherStr .
} INSERT {
	?s dcterms:publisher ?publisher .
} WHERE {
	?s a dcat:Dataset ;
		dcterms:publisher ?publisherStr .
	
	?publisher a dcterms:Publisher ;
		foaf:name ?publisherStr .
};

# replace dataset distribution uris
DELETE {
	?dataset dcat:distribution ?distributionStr .
} INSERT {
	?dataset dcat:distribution ?distribution .
} WHERE {
	?dataset a dcat:Dataset ;
		dcat:distribution ?distributionStr .

	?distribution a dcat:Distribution ;
		dcterms:format ?distributionStr .
};