PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX hwbp: <https://hse-oahwb-profile.adaptcentre.ie#>
PREFIX healthdcatap: <http://example.org/healthdcatap#>

SELECT 
  ?indicator
  ?title
  ?accrualPeriodicity
  ?identifier
  ?numeratorSource
  ?disaggregation
  ?numeratorDataElement
  ?denominatorDataElement
  ?denominatorSource
  ?healthThemeDomain
  ?healthThemeSubdomain
  (
    (
      (IF(BOUND(?accrualPeriodicity),1,0) +
       IF(BOUND(?identifier),1,0) +
       IF(BOUND(?numeratorSource),1,0) +
       IF(BOUND(?disaggregation),1,0) +
       IF(BOUND(?numeratorDataElement),1,0) +
       IF(BOUND(?denominatorDataElement),1,0) +
       IF(BOUND(?denominatorSource),1,0) +
       IF(BOUND(?healthThemeDomain),1,0) +
       IF(BOUND(?healthThemeSubdomain),1,0)
      ) / 9.0
    ) * 100 AS ?percentPresent
  )
WHERE {
  ?indicator a dcat:Dataset ;
    dcterms:title ?title .
  OPTIONAL { ?indicator dcterms:accrualPeriodicity ?accrualPeriodicity . }
  OPTIONAL { ?indicator dcterms:identifier ?identifier . }
  OPTIONAL { ?indicator hwbp:disaggregation ?disaggregation . }
  OPTIONAL { ?indicator hwbp:numeratorDataElement ?numeratorDataElement . }
  OPTIONAL { ?indicator hwbp:numeratorSource ?numeratorSource . }
  OPTIONAL { ?indicator hwbp:denominatorDataElement ?denominatorDataElement . }
  OPTIONAL { ?indicator hwbp:denominatorSource ?denominatorSource . }
  OPTIONAL { ?indicator healthdcatap:healthTheme ?healthThemeDomain . 
      ?healthThemeDomain a healthdcatap:Domain . }
  OPTIONAL { ?indicator healthdcatap:healthTheme ?healthThemeSubdomain . 
      ?healthThemeSubdomain a healthdcatap:Subdomain . }
}