PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX ddc: <http://purl.org/NET/decimalised#>
PREFIX dpv: <https://w3id.org/dpv#>
PREFIX dcterm: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX adms: <http://www.w3.org/ns/adms#>
PREFIX dcterms: <http://purl.org/dc/terms/>
prefix dc: <http://purl.org/dc/elements/1.1/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX : <https://hse.ie/>
PREFIX phi: <https://hse.ie/ontology/phi#>
PREFIX phd: <https://hse.ie/ontology/phd#>
PREFIX phpt: <https://hse.ie/terminology/phpt#>
PREFIX healthdcatap: <http://healthdata.dublinked.ie/def/healthdcatap#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT 
?indicator 
?indicatorTitle
?pass
?dq_score
?valid_dataset
?1_1_pass
?1_1_note
?1_7_pass
?1_7_note
?1_7_warning
?2_1_pass
?2_1_note
?2_1_warning
?2_2_pass
?2_2_note
?2_2_warning
?3_1_pass
?3_1_note
?3_1_warning
?4_1_pass
?4_1_warning
?4_2_pass
?4_2_warning
?4_3_pass
?4_3_warning
?data_protection_pass
?data_protection_warning
WHERE {
  ?indicator a phi:Indicator ;
  a dcat:Dataset .
  ?indicator dcterms:title ?indicatorTitle .

  OPTIONAL { ?indicator dcterms:accrualPeriodicity/phd:frequencyValue ?indicatorAccrualPeriodicity . }
  OPTIONAL { ?indicator phi:disaggregation ?disaggregation . }
  OPTIONAL { ?indicator dcterms:identifier ?identifier . }

  OPTIONAL { 
    ?indicator  phi:numeratorSource ?numeratorSource .

    OPTIONAL { ?numeratorSource dcat:temporalResolution ?temporalResolution . }
    OPTIONAL { ?numeratorSource phd:spatialAggregation ?spatialAggregation . }
    OPTIONAL { ?numeratorSource dcterms:accrualPeriodicity/phd:frequencyValue ?datasetAccrualPeriodicity . }

    OPTIONAL { ?numeratorSource dpv:hasPersonalData ?hasPersonalData . }
    OPTIONAL { ?numeratorSource dcterms:accessRights ?accessRight . }
    OPTIONAL { ?numeratorSource dpv:hasDataController ?hasDataController . }
    OPTIONAL { ?numeratorSource healthdcatap:maxTypicalAge ?maxTypicalAge . }
  }

  # Q 4.1
  BIND(IF(!BOUND(?hasPersonalData), 'unknown',
      IF(?hasPersonalData = dpv:NonPersonalData, "true", "false")
    ) AS ?4_1_pass)
  BIND(IF(?4_1_pass = 'unknown', "Q4.1: Personal Data field not present", 
      IF(?4_1_pass = 'true', "", "Q4.1: Indicator w/ Dataset contains personal/sensitive data")
    ) AS ?4_1_warning)

  # Q 4.2
  BIND(IF(!BOUND(?hasPersonalData), 'unknown', IF(?hasPersonalData = dpv:NonPersonalData, "true", "false")) AS ?4_2_pass)
  BIND(IF(?4_2_pass = 'unknown', "Q4.2: Personal Data field not present",
      IF(?4_2_pass = 'true', "", "Q4.2: Indicator w/ Dataset contains personal/sensitive data")
    ) AS ?4_2_warning)

  # Q 4.3
  BIND(IF(!BOUND(?hasDataController), 'unknown', 
      IF(?hasDataController = "HSE", "true", "false")
    ) AS ?4_3_pass)
  BIND(IF(?4_3_pass = 'unknown', "Q4.3: Data Controller field not present",
      IF(?4_3_pass = 'true', "", "Q4.3: Indicator w/ Dataset contains personal/sensitive data that is not controlled by HSE")
    ) AS ?4_3_warning)

  # overall data protection pass
  BIND(IF((?4_1_pass = 'true' && ?4_2_pass = 'true' && ?4_3_pass = 'true'), "true", 
      IF((?4_1_pass = 'unknown' || ?4_2_pass = 'unknown' || ?4_3_pass = 'unknown'), "unknown", "false")
    ) AS ?data_protection_pass)

  # concat all data protection warnings
  BIND(CONCAT(
      IF(?4_1_warning != "", CONCAT(?4_1_warning, '; '), ""),
      IF(?4_2_warning != "", CONCAT(?4_2_warning, '; '), ""),
      IF(?4_3_warning != "", ?4_3_warning, "")
    ) AS ?data_protection_warning)

  # with dataset?
  BIND(BOUND(?numeratorSource) && isURI(?numeratorSource) AS ?valid_dataset)
  BIND(IF(?valid_dataset, '', 'Indicator w/o a valid or linked Dataset') AS ?dataset_note)

  # 1.7 - disaggregation
  BIND(IF(!BOUND(?disaggregation), "unknown", IF(CONTAINS(LCASE(STR(?disaggregation)), "65"), "true", "false")) AS ?disaggregation_pass)
  BIND(IF(!BOUND(?disaggregation), "Q1.7: Disaggregation not present", "") AS ?disaggregation_warning)
  BIND(IF(CONTAINS(LCASE(STR(?disaggregation)), "65"), "", "Q1.7: disaggregation field don't have data for people aged over 65 ") AS ?disaggregation_note)

  # 1.7 - max typical age
  BIND(IF(!BOUND(?maxTypicalAge), "unknown", IF(xsd:integer(?maxTypicalAge) >= 65, "true", "false")) AS ?maxAge_pass)
  BIND(IF(!BOUND(?maxTypicalAge), "Q1.7: Maximum Typical Age not present", "") AS ?maxAge_warning)
  BIND(IF(xsd:integer(?maxTypicalAge) >= 65, "", "Q1.7: Maximum Typical Age < 65") AS ?maxAge_note)

  # 1.7 check disaggregation and max typical age
  BIND(IF(?disaggregation_pass = "true" || ?maxAge_pass = "true", "true", 
      IF(?disaggregation_pass = "unknown" || ?maxAge_pass = "unknown", "unknown", "false")
    ) AS ?1_7_pass)
  BIND(CONCAT(?disaggregation_warning, ?maxAge_warning) AS ?1_7_warning)
  BIND(CONCAT(?disaggregation_note, ?maxAge_note) AS ?1_7_note)

  # 2.1
  BIND(IF(BOUND(?temporalResolution), "true", "unknown") AS ?2_1_pass)
  BIND(IF(BOUND(?temporalResolution), "", "Q2.1: Minimal Temporal resolution not present") AS ?2_1_warning)
  BIND("" AS ?2_1_note)

  # 2.2
  BIND(IF(!BOUND(?spatialAggregation), "unknown", 
      IF(?spatialAggregation = phpt:National || ?spatialAggregation = phpt:IHA || ?spatialAggregation = phpt:NUTS1, "true", "false")) 
    AS ?2_2_pass)
  BIND(
    IF(!BOUND(?spatialAggregation), "Q2.2: Spatial Resolution Code not present", 
    IF(?spatialAggregation = phpt:National || ?spatialAggregation = phpt:IHA || ?spatialAggregation = phpt:NUTS1, "", "Q2.2: indicators w/ dataset don't have spatial resolution of National, IHA or NUTS1")) 
    AS ?2_2_warning)
  BIND("" AS ?2_2_note)

  # 3.1 values for accrual periodicity: EVERY_5_YEARS, EVERY_4_YEARS, EVERY_3_YEARS, EVERY_2_YEARS, ANNUAL, DAILY, MONTHLY, QUARTERLY, WEEKLY, NEVER, AS_NEEDED
  BIND(IF(!BOUND(?indicatorAccrualPeriodicity), "unknown", 
      IF(!BOUND(?datasetAccrualPeriodicity), "unknown", 
        IF(?indicatorAccrualPeriodicity >= ?datasetAccrualPeriodicity, "true", "false")))
    AS ?3_1_pass)
  BIND(IF(!BOUND(?indicatorAccrualPeriodicity), "Q3.1: Indicator Report Frequency not present", "") AS ?3_1_indicator_warning)
  BIND(IF(!BOUND(?datasetAccrualPeriodicity), "Q3.1: Dataset Update Frequency not present", "") AS ?3_1_dataset_warning)
  BIND(CONCAT(?3_1_indicator_warning, ?3_1_dataset_warning) AS ?3_1_warning)
  BIND(IF(?indicatorAccrualPeriodicity >= ?datasetAccrualPeriodicity, "", "Q3.1: Numerator dataset does not have update frequency required by indicator") AS ?3_1_note)

  # 1.1 required fields
  BIND(BOUND(?indicatorTitle) AS ?titlePresent)
  BIND(BOUND(?identifier) AS ?identifierPresent)
  BIND(BOUND(?indicatorAccrualPeriodicity) AS ?accrualPeriodicityPresent)
  BIND(BOUND(?numeratorSource) AS ?numeratorSourcePresent)
  BIND(BOUND(?disaggregation) AS ?disaggregationPresent)

  BIND(BOUND(?temporalResolution) AS ?temporalResolutionPresent)
  BIND(BOUND(?spatialAggregation) AS ?spatialAggregationPresent)
  BIND(BOUND(?datasetAccrualPeriodicity) AS ?datasetAccrualPeriodicityPresent)
  BIND(BOUND(?hasPersonalData) AS ?hasPersonalDataPresent)
  BIND(BOUND(?hasDataController) AS ?hasDataControllerPresent)
  BIND(BOUND(?maxTypicalAge) AS ?maxTypicalAgePresent)

  BIND(IF(
      ?titlePresent && 
      ?identifierPresent && 
      ?accrualPeriodicityPresent && 
      ?numeratorSourcePresent && 
      ?disaggregationPresent && 
      ?temporalResolutionPresent && 
      ?spatialAggregationPresent &&
      ?datasetAccrualPeriodicityPresent && 
      ?hasPersonalDataPresent && 
      ?hasDataControllerPresent && 
      ?maxTypicalAgePresent, true, false) AS ?1_1_pass)
  BIND(IF(?1_1_pass, "", "Q1.1: Indicator w/ Dataset missing one or more required fields") AS ?1_1_note)

  # overall pass
  BIND(IF((?1_1_pass && ?2_1_pass = "true"), "true", 
      IF((!?1_1_pass && ?2_1_pass = "false"), "false", "unknown")
    ) AS ?pass)

  # DQ score
  BIND(IF(?1_1_pass, 1, 0) + IF(?2_1_pass = "true", 1, 0) AS ?num_pass)
  BIND(?num_pass/2 AS ?dq_score)
}
ORDER BY ASC(?indicator)